# Generated by Django 2.2.7 on 2019-12-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusGo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('go_bus_number', models.CharField(max_length=10)),
                ('go_station_id', models.CharField(max_length=20)),
                ('go_route_id', models.CharField(max_length=20)),
                ('go_station_order', models.CharField(max_length=5)),
                ('go_region', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BusOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=20)),
                ('out_bus_number', models.CharField(max_length=10)),
                ('out_station_id', models.CharField(max_length=20)),
                ('out_route_id', models.CharField(max_length=20)),
                ('out_station_order', models.CharField(max_length=5)),
                ('out_region', models.CharField(max_length=10)),
            ],
        ),
    ]
